import type { Creative } from "./types";

/**
 * Demo dataset used when NEXT_PUBLIC_USE_MOCK=true (or when no API URL is set).
 * Mirrors the backend contract. All timestamps are ISO strings; the list is
 * sorted by lastEditedAt (most recently edited on Notion first).
 */
export const MOCK_PRODUCTS: Creative[] = [
  {
    id: "6b24f03d-d915-4f17-b160-9676b036b316",
    name: "V48",
    brand: "NUMY",
    product: "Bold",
    status: "in_progress",
    generationStatus: "completed",
    angle: "Stress relief",
    awareness: "Problem aware",
    audience: "Overwhelmed professionals",
    problem:
      "Chronic stress keeps the nervous system stuck in fight-or-flight, killing desire and intimacy.",
    desire: "A real off switch — to finally relax, reconnect, and feel like themselves again.",
    hook: "Always on?",
    hypothesis:
      "Bio-identifying stress as the root cause of low desire will beat lifestyle 'hacks' copy.",
    headlines: [
      "Always 'on'? Bold is your off switch.",
      "Biologically blocked by stress?",
      "An orgasm is a recovery mechanism.",
      "Reset your stuck stress system.",
      "Force your body out of stress mode.",
    ],
    primary_texts: [
      "Your nervous system can't think itself into relaxation. Stress keeps it stuck in 'on' — and that blocks your body's natural reset, your sleep, and even your desire. Bold works on the mechanism, not the mindset.",
      "You're not weak — you're biologically blocked. When stress floods your system, the chemistry your body needs for relaxation and intimacy never fires. Bold addresses the root, not the symptom.",
      "An orgasm is not a luxury — it's a recovery mechanism. It's the one thing that tells your nervous system the danger is over. Bold helps you actually get there when stress keeps pulling you back.",
    ],
    lastEditedAt: "2026-08-11T09:40:00.000Z",
    generatedAt: "2026-08-11T09:39:00.000Z",
  },
  {
    id: "v22-batch-0000-0000-0000-000000000001",
    name: "V22",
    brand: "NUMY",
    product: "Bold",
    status: "in_progress",
    generationStatus: "completed",
    angle: "Stress relief",
    awareness: "Problem aware",
    audience: "Chronically stressed women",
    problem:
      "Stress keeps the body stuck in 'on', blocking relaxation, sleep and desire.",
    desire: "To finally switch off, unwind and feel like themselves again.",
    hook: "Always on?",
    headlines: [
      "Wired but tired? Here's why.",
      "Your 10-minute nightly reset.",
      "Sleep isn't a luxury — it's mechanics.",
      "The off switch your brain forgot.",
      "Wake up restored, not recharged.",
    ],
    primary_texts: [
      "You fall into bed exhausted but your brain won't shut up. That's not a discipline problem — it's a chemistry problem. This routine gives your nervous system the signal it needs to actually power down.",
    ],
    lastEditedAt: "2026-08-11T08:20:00.000Z",
    generatedAt: "2026-08-11T08:18:00.000Z",
  },
  {
    id: "7c8e1a2b-3d4e-4f5a-8b6c-1d2e3f4a5b6c",
    name: "V22 C1 ENG",
    brand: "NUMY",
    product: "Bold",
    status: "in_progress",
    generationStatus: "idle",
    parentItem: ["v22-batch-0000-0000-0000-000000000001"],
    angle: "Sleep & recovery",
    awareness: "Problem aware",
    audience: "Chronically stressed women",
    problem:
      "Restless nights and wired brains that won't switch off — even when the day is over.",
    desire: "To actually unwind at night and wake up feeling restored.",
    hook: "Wired but tired?",
    hypothesis:
      "Framing Bold as a nightly recovery ritual will out-perform generic sleep-hygiene copy.",
    headlines: [],
    primary_texts: [],
    lastEditedAt: "2026-08-11T08:15:00.000Z",
    generatedAt: null,
  },
  {
    id: "a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d",
    name: "V22 C2 ENG",
    brand: "NUMY",
    product: "Bold",
    status: "checkpoint",
    generationStatus: "completed",
    parentItem: ["v22-batch-0000-0000-0000-000000000001"],
    angle: "Confidence",
    awareness: "Solution aware",
    audience: "Low-desire women",
    problem:
      "Feeling disconnected from your body and losing confidence in the bedroom.",
    desire: "To feel desire again without pressure or performance.",
    hook: "Desire isn't a switch — it's chemistry.",
    headlines: [
      "Desire isn't a switch — it's chemistry.",
      "Your body remembers how to feel good.",
      "Why 'just relax' never works.",
      "Reconnect with the version of you that felt alive.",
      "The 10-minute reset your evenings are missing.",
    ],
    primary_texts: [
      "When stress has kept you in 'survive' mode, desire doesn't come back just because you want it to. Bold rebuilds the chemistry your body needs to feel turned on again — without pressure, without performance.",
      "The more pressure you feel to 'fix' it, the more your nervous system digs in. That's why willpower alone fails. Bold works at the biological layer, so your body can finally come back online.",
      "You're not broken — you're overloaded. Give your nervous system the exact signal it needs and the rest follows. That's what Bold does, and why thousands of women use it nightly.",
    ],
    lastEditedAt: "2026-08-10T16:02:00.000Z",
    generatedAt: "2026-08-10T15:58:00.000Z",
  },
  {
    id: "f6e5d4c3-b2a1-4f0e-9d8c-7b6a5f4e3d2c",
    name: "V22 C3 ENG",
    brand: "NUMY",
    product: "Bold",
    status: "not_started",
    generationStatus: "idle",
    parentItem: ["v22-batch-0000-0000-0000-000000000001"],
    angle: "Body confidence",
    awareness: "Solution aware",
    audience: "Post-natal mums",
    problem:
      "Motherhood rewired her body and her desire — and nobody told her that was normal.",
    desire: "To feel like herself in her own skin again.",
    hook: null,
    hypothesis:
      "Post-natal resonance copy will drive the highest CTR among 28-40 women.",
    headlines: [],
    primary_texts: [],
    lastEditedAt: "2026-08-09T11:00:00.000Z",
    generatedAt: null,
  },
  {
    id: "e5d4c3b2-a1b0-4c9d-8e7f-6a5b4c3d2e1f",
    name: "V22 C5 ENG",
    brand: "NUMY",
    product: "Bold",
    status: "revision",
    generationStatus: "idle",
    parentItem: ["v22-batch-0000-0000-0000-000000000001"],
    angle: "Stress relief",
    awareness: "Unaware",
    audience: "Overwhelmed professionals",
    problem:
      "Stress is wrecking their recovery without them realizing the link.",
    desire: "Better sleep and mood — without another pill.",
    hook: "Always on?",
    headlines: [],
    primary_texts: [],
    lastEditedAt: "2026-08-08T14:22:00.000Z",
    generatedAt: null,
  },
  {
    id: "b111-batch-0000-0000-0000-000000000001",
    name: "B111",
    brand: "HOLY MOUTHWASH",
    product: "Halo Pulling Oil",
    status: "in_progress",
    generationStatus: "idle",
    angle: "Oral care",
    awareness: "Solution aware",
    audience: "Gum-bleed sufferers",
    problem:
      "Brushing, flossing and deep cleanings — gums still bleeding.",
    desire: "A gum routine that finally works.",
    hook: "Quoted £2,000 for gum surgery?",
    headlines: [],
    primary_texts: [],
    lastEditedAt: "2026-08-07T17:50:00.000Z",
    generatedAt: null,
  },
  {
    id: "d4c3b2a1-0b9c-8d7e-6f5a-4b3c2d1e0f9a",
    name: "B111 C1 ENG",
    brand: "HOLY MOUTHWASH",
    product: "Halo Pulling Oil",
    status: "not_started",
    generationStatus: "failed",
    parentItem: ["b111-batch-0000-0000-0000-000000000001"],
    angle: "Oral care",
    awareness: "Solution aware",
    audience: "Gum-bleed sufferers",
    problem:
      "Brushing, flossing and deep cleanings — gums still bleeding.",
    desire: "A gum routine that finally works.",
    hook: "Quoted £2,000 for gum surgery?",
    headlines: [],
    primary_texts: [],
    lastEditedAt: "2026-08-07T17:45:00.000Z",
    generatedAt: null,
  },
  {
    id: "c2d3e4f5-6a7b-8c9d-0e1f-2a3b4c5d6e7f",
    name: "C101-01",
    brand: "SORALUNE",
    product: "Silk Serum",
    status: "revision",
    generationStatus: "completed",
    angle: "Glow",
    awareness: "Product aware",
    audience: "Skincare enthusiasts",
    problem: "Barrier damage from over-exfoliation leaves skin dull and reactive.",
    desire: "A dewy, calm, glass-skin glow without stripping.",
    hook: "Glass skin, minus the damage.",
    headlines: [
      "Glass skin, minus the damage.",
      "Your barrier is not a scrub pad.",
      "Glow that survives winter.",
      "The serum your skin accepts.",
      "Dullness out. Dew in.",
    ],
    primary_texts: [
      "Every 'glow' routine that strips your barrier is borrowing from tomorrow. Silk Serum rebuilds the barrier first — so the glow you get is the glow you keep.",
      "Over-exfoliated skin doesn't need more actives, it needs repair. Silk feeds the barrier, calms the reactivity, and lets your natural glow come back on its own.",
    ],
    lastEditedAt: "2026-08-06T10:30:00.000Z",
    generatedAt: "2026-08-06T10:12:00.000Z",
  },
];
